#AZFUSE_USE_FUSE=0 QD_USE_LINEIDX_4B=0 NCCL_ASYNC_ERROR_HANDLING=0 python finetune_sdm_yaml.py --cf config/ref_attn_clip_combine_controlnet_attr_pretraining/coco_S256_xformers_tsv_strongrand.py --do_train --root_dir /media/namrata/Projects/Yeshiva/3d_pose_generation --local_train_batch_size 4 --local_eval_batch_size 4 --log_dir exp/tiktok_pretrain12 --epochs 4 --deepspeed --use_amp --eval_step 50 --save_step 50 --gradient_accumulate_steps 4 --learning_rate 1e-3 --fix_dist_seed --loss_target "noise" --train_yaml dataset/TikTok_finetuning/composite_offset/train_TiktokDance-poses-masks.yaml --val_yaml dataset/TikTok_finetuning/composite_offset/new10val_TiktokDance-poses-masks.yaml --unet_unfreeze_type "transblocks" --refer_sdvae --ref_null_caption False --combine_clip_local --combine_use_mask --conds "masks" --max_eval_samples 100 --strong_aug_stage1 --node_split_sampler 0

AZFUSE_USE_FUSE=0 NCCL_ASYNC_ERROR_HANDLING=0 python finetune_sdm_yaml.py --cf config/disco_w_tm/yz_tiktok_S256L16_xformers_tsv_temdisco_temp_attn.py --do_train --root_dir /scratch/namrata/3d_pose_gen --local_train_batch_size 2 --local_eval_batch_size 2 --log_dir exp/tiktok_ft8 --epochs 1 --deepspeed --eval_step 100 --save_step 100 --gradient_accumulate_steps 1 --learning_rate 1e-4 --fix_dist_seed --loss_target "noise" --train_yaml dataset/TikTok_finetuning/composite_offset/train_TiktokDance-poses-masks.yaml --val_yaml dataset/TikTok_finetuning/composite_offset/new10val_TiktokDance-poses-masks.yaml --unet_unfreeze_type "crossattn" --refer_sdvae --ref_null_caption False --combine_clip_local --combine_use_mask --train_sample_interval 4 --nframe 16 --frame_interval 1 --guidance_scale 3 --conds "poses" "masks" --stage1_pretrain_path dataset/disco/ft_checkpoint/moretiktok_nocfg/mp_rank_00_model_states.pt 


--pretrained_model_path


WANDB_ENABLE=0 AZFUSE_USE_FUSE=0 NCCL_ASYNC_ERROR_HANDLING=0 python finetune_sdm_yaml.py --cf config/ref_attn_clip_combine_controlnet/tiktok_S256L16_xformers_tsv.py --do_train --root_dir /scratch/namrata/3d_pose_gen --local_train_batch_size 32 --local_eval_batch_size 32 --log_dir exp/tiktok_ft12 --epochs 4 --deepspeed --eval_step 1000 --save_step 1000 --gradient_accumulate_steps 2 --learning_rate 2e-4 --fix_dist_seed --loss_target "noise" --train_yaml /scratch/namrata/3d_pose_gen/dataset/Tiktok_finetuning/composite_offset/train_TiktokDance-poses-masks.yaml --val_yaml /scratch/namrata/3d_pose_gen/dataset/Tiktok_finetuning/composite_offset/new10val_TiktokDance-poses-masks.yaml --unet_unfreeze_type "crossattn" --guidance_scale 3 --refer_sdvae --ref_null_caption False --combine_clip_local --combine_use_mask --conds "poses" "masks" --stage1_pretrain_path dataset/disco/ft_checkpoint/moretiktok_nocfg/mp_rank_00_model_states.pt 


AZFUSE_USE_FUSE=0 QD_USE_LINEIDX_8B=0 NCCL_ASYNC_ERROR_HANDLING=0 python finetune_sdm_yaml.py --cf config/ref_attn_clip_combine_controlnet_attr_pretraining/coco_S256_xformers_tsv_strongrand.py --do_train --root_dir /scratch/namrata/3d_pose_gen --local_train_batch_size 64 --local_eval_batch_size 64 --log_dir exp/tiktok_ft14 --epochs 10 --deepspeed --eval_step 2000 --save_step 2000 --gradient_accumulate_steps 1 --learning_rate 1e-3 --fix_dist_seed --loss_target "noise" --train_yaml dataset/coco/train_coco_single_person.yaml --val_yaml dataset/coco/val_coco_single_person.yaml --unet_unfreeze_type "transblocks" --refer_sdvae --ref_null_caption False --combine_clip_local --combine_use_mask --conds "masks" --max_eval_samples 500 --strong_aug_stage1 --node_split_sampler 0

## ORIGINAL TRAINING PROCESS : LAST RUN ###
WANDB_ENABLE=0 CUDA_LAUNCH_BLOCKING=1 AZFUSE_USE_FUSE=0 NCCL_ASYNC_ERROR_HANDLING=0 python finetune_sdm_yaml.py --cf config/ref_attn_clip_combine_controlnet/tiktok_S256L16_xformers_tsv.py --do_train --root_dir /scratch/namrata/3d_pose_gen --local_train_batch_size 4 --local_eval_batch_size 4 --log_dir exp/tiktok_ft22 --epochs 10 --deepspeed --eval_step 500 --save_step 500 --gradient_accumulate_steps 4 --learning_rate 1e-3 --fix_dist_seed --loss_target "noise" --train_yaml /scratch/namrata/3d_pose_gen/dataset/Tiktok_finetuning/composite_offset/train_TiktokDance-poses-masks.yaml --val_yaml /scratch/namrata/3d_pose_gen/dataset/Tiktok_finetuning/composite_offset/new10val_TiktokDance-poses-masks.yaml --unet_unfreeze_type "all" --guidance_scale 2 --refer_sdvae --ref_null_caption False --combine_clip_local --combine_use_mask --conds "poses" "masks" --stage1_pretrain_path /scratch/namrata/3d_pose_gen/dataset/disco/ft_checkpoint/moretiktok_nocfg/mp_rank_00_model_states.pt --constant_lr 



AZFUSE_USE_FUSE=0 NCCL_ASYNC_ERROR_HANDLING=0 python finetune_sdm_yaml.py --cf config/disco_w_tm/yz_tiktok_S256L16_xformers_tsv_temdisco_temp_attn.py --do_train --root_dir /scratch/namrata/3d_pose_gen --local_train_batch_size 2 --local_eval_batch_size 2 --log_dir exp/tiktok_ft --epochs 20 --deepspeed --eval_step 500 --save_step 500 --gradient_accumulate_steps 1 --learning_rate 1e-4 --fix_dist_seed --loss_target "noise" --train_yaml /scratch/namrata/3d_pose_gen/dataset/Tiktok_finetuning/composite_offset/train_TiktokDance-poses-masks.yaml --val_yaml /scratch/namrata/3d_pose_gen/dataset/Tiktok_finetuning/composite_offset/new10val_TiktokDance-poses-masks.yaml --unet_unfreeze_type "all" --refer_sdvae --ref_null_caption False --combine_clip_local --combine_use_mask --train_sample_interval 4 --nframe 16 --frame_interval 1 --conds "poses" "masks" --pretrained_model /scratch/namrata/3d_pose_gen/dataset/disco/ft_checkpoint/moretiktok_nocfg/mp_rank_00_model_states.pt  

#CURRENT


WANDB_ENABLE=0 AZFUSE_USE_FUSE=0 NCCL_ASYNC_ERROR_HANDLING=0 python finetune_sdm_yaml.py --cf config/ref_attn_clip_combine_controlnet_attr_pretraining/coco_S256_xformers_tsv.py --do_train --root_dir /scratch/namrata/3d_pose_gen --local_train_batch_size 32 --local_eval_batch_size 32 --log_dir exp/tiktok_ft12 --epochs 4 --deepspeed --eval_step 1000 --save_step 1000 --gradient_accumulate_steps 2 --learning_rate 1e-7 --fix_dist_seed --loss_target "noise" --train_yaml /scratch/namrata/3d_pose_gen/dataset/Tiktok_finetuning/composite_offset/train_TiktokDance-poses-masks.yaml --val_yaml /scratch/namrata/3d_pose_gen/dataset/Tiktok_finetuning/composite_offset/new10val_TiktokDance-poses-masks.yaml --unet_unfreeze_type "crossattn" --guidance_scale 3 --refer_sdvae --ref_null_caption False --combine_clip_local --combine_use_mask --conds "poses" "masks" --stage1_pretrain_path dataset/disco/ft_checkpoint/moretiktok_nocfg/mp_rank_00_model_states.pt 

#Process ID : 1900614